name: Automated
description: Automated handle
author: oobook
branding:
  icon: target
  color: yellow
inputs:
  test:
    description: run mode of the action
    required: false
    default: false
  # gh-token:
  #   description: GitHub token with repo access
  #   required: true
runs:
  using: node20
  main: dist/index.js
